### ISSUE TITLE
Does this tool support editing resources in macOS intel executable (mach-O format) ?

### ISSUE THREAD

**Issue by Fernando2018s** [jcfr/ResEdit#9]
Hi are you working with intel macos?

_Publicado originalmente por @onuratakan en https://github.com/onuratakan/gpt-computer-assistant/issues/10#issuecomment-2145988465_

**Comment by jcfr** [comment]
Since this tool only aims to update resources within an already compiled windows executable (PE format[^1]), supporting intel macOS executable (Mach-O format[^2]) will not be implemented.

For the macOS support, you may want to look into tools like ResForge[^4]

Note that despite its name, this project is different form the other "ResEdit" project discontinued[^3] in 1994. 

[^1]: https://en.wikipedia.org/wiki/Portable_Executable
[^2]: https://en.wikipedia.org/wiki/Mach-O
[^3]: https://en.wikipedia.org/wiki/ResEdit
[^4]: https://github.com/andrews05/ResForge

**Comment by jcfr** [comment]
@onuratakan @Fernando2018s  If you do not need any additional clarifications, I suggest you close this issue. :pray:

**Comment by jcfr** [comment]
If you have any other questions, please open a new issue.

In the meantime, I will go ahead and close this one.

**Comment by Fernando2018s** [comment]
> Hi are you working with intel macos?
> 
> _Publicado originalmente por @onuratakan en https://github.com/onuratakan/gpt-computer-assistant/issues/10#issuecomment-2145988465_
